import { describe, it, expect } from 'vitest';
import { WhisperMelProcessor } from '../src/audio/whisper-mel.js';
import * as fs from 'fs';

/**
 * Validate WhisperMelProcessor against OpenAI reference output.
 *
 * Reference data is generated by Python openai-whisper for a 1s 440Hz sine
 * at 16kHz. The fixture file must be present; if absent, the test skips.
 */

const REF_PATH = '/tmp/whisper_mel_ref_440hz_1s.json';

interface RefData {
  shape: number[];
  data: number[][];
}

function loadRef(): RefData | null {
  try {
    const raw = fs.readFileSync(REF_PATH, 'utf-8');
    return JSON.parse(raw) as RefData;
  } catch {
    return null;
  }
}

describe('WhisperMelProcessor vs OpenAI reference', () => {
  it('produces mel features matching OpenAI within tolerance', () => {
    const ref = loadRef();
    if (!ref) {
      console.warn(`Skipping: reference fixture not found at ${REF_PATH}`);
      return;
    }

    const sampleRate = 16000;
    const samples = new Float32Array(sampleRate);
    for (let i = 0; i < sampleRate; i++) {
      samples[i] = Math.sin((2 * Math.PI * 440 * i) / sampleRate);
    }

    const processor = new WhisperMelProcessor({ nMels: 80, sampleRate });
    const result = processor.process(samples);

    expect(result.nMels).toBe(80);
    expect(result.frameCount).toBe(ref.shape[1]);
    expect(result.features.length).toBe(80 * ref.shape[1]);

    const nFrames = Math.min(result.frameCount, ref.shape[1]);
    let maxDiff = 0;
    let totalDiff = 0;
    for (let mel = 0; mel < 80; mel++) {
      for (let frame = 0; frame < nFrames; frame++) {
        const ours = result.features[mel * result.frameCount + frame] as number;
        const theirs = ref.data[mel][frame];
        const diff = Math.abs(ours - theirs);
        totalDiff += diff;
        if (diff > maxDiff) maxDiff = diff;
      }
    }

    const avgDiff = totalDiff / (80 * nFrames);
    console.log(`maxDiff=${maxDiff.toExponential(3)} avgDiff=${avgDiff.toExponential(3)}`);

    // Tolerance: max diff should be < 1e-3 (numerical precision between
    // float64 Python and float32 TypeScript plus DFT vs FFT differences)
    expect(maxDiff).toBeLessThan(1e-3);
    expect(avgDiff).toBeLessThan(1e-4);
  });
});
